# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: glm-5.2
    provider: nvidia
    model: glm-5.2
    apiKey: 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
    roles:
      - chat
      - edit
      - apply
  s